version: '2.1'
orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWSAccessKeyId
          aws-cli-version: latest
          aws-secret-access-key: AWSSecretKey
          create-repo: true
          dockerfile: Dockerfile
          executor: aws-ecr/default
          path: .
          platform: linux/amd64
          public-registry: false
          push-image: true
          region: AWS_REGION
          repo: catherinepope
